export default [
  {gender: "male", name: "Adán"},
  {gender: "male", name: "Agustín"},
  {gender: "male", name: "Alberto"},
  {gender: "male", name: "Alejandro"},
  {gender: "male", name: "Alfonso"},
  {gender: "male", name: "Alfredo"},
  {gender: "male", name: "Andrés"},
  {gender: "male", name: "Antonio"},
  {gender: "male", name: "Armando"},
  {gender: "male", name: "Arturo"},
  {gender: "male", name: "Benito"},
  {gender: "male", name: "Benjamín"},
  {gender: "male", name: "Bernardo"},
  {gender: "male", name: "Carlos"},
  {gender: "male", name: "César"},
  {gender: "male", name: "Claudio"},
  {gender: "male", name: "Clemente"},
  {gender: "male", name: "Cristian"},
  {gender: "male", name: "Cristobal"},
  {gender: "male", name: "Daniel"},
  {gender: "male", name: "David"},
  {gender: "male", name: "Diego"},
  {gender: "male", name: "Eduardo"},
  {gender: "male", name: "Emilio"},
  {gender: "male", name: "Enrique"},
  {gender: "male", name: "Ernesto"},
  {gender: "male", name: "Esteban"},
  {gender: "male", name: "Federico"},
  {gender: "male", name: "Felipe"},
  {gender: "male", name: "Fernando"},
  {gender: "male", name: "Francisco"},
  {gender: "male", name: "Gabriel"},
  {gender: "male", name: "Gerardo"},
  {gender: "male", name: "Germán"},
  {gender: "male", name: "Gilberto"},
  {gender: "male", name: "Gonzalo"},
  {gender: "male", name: "Gregorio"},
  {gender: "male", name: "Guillermo"},
  {gender: "male", name: "Gustavo"},
  {gender: "male", name: "Hernán"},
  {gender: "male", name: "Homero"},
  {gender: "male", name: "Horacio"},
  {gender: "male", name: "Hugo"},
  {gender: "male", name: "Ignacio"},
  {gender: "male", name: "Jacobo"},
  {gender: "male", name: "Jaime"},
  {gender: "male", name: "Javier"},
  {gender: "male", name: "Jerónimo"},
  {gender: "male", name: "Jesús"},
  {gender: "male", name: "Joaquín"},
  {gender: "male", name: "Jorge"},
  {gender: "male", name: "Jorge Luis"},
  {gender: "male", name: "José"},
  {gender: "male", name: "José Eduardo"},
  {gender: "male", name: "José Emilio"},
  {gender: "male", name: "José Luis"},
  {gender: "male", name: "José María"},
  {gender: "male", name: "Juan"},
  {gender: "male", name: "Juan Carlos"},
  {gender: "male", name: "Julio"},
  {gender: "male", name: "Julio César"},
  {gender: "male", name: "Lorenzo"},
  {gender: "male", name: "Lucas"},
  {gender: "male", name: "Luis"},
  {gender: "male", name: "Luis Miguel"},
  {gender: "male", name: "Manuel"},
  {gender: "male", name: "Marco Antonio"},
  {gender: "male", name: "Marcos"},
  {gender: "male", name: "Mariano"},
  {gender: "male", name: "Mario"},
  {gender: "male", name: "Martín"},
  {gender: "male", name: "Mateo"},
  {gender: "male", name: "Miguel"},
  {gender: "male", name: "Miguel Ángel"},
  {gender: "male", name: "Nicolás"},
  {gender: "male", name: "Octavio"},
  {gender: "male", name: "Óscar"},
  {gender: "male", name: "Pablo"},
  {gender: "male", name: "Patricio"},
  {gender: "male", name: "Pedro"},
  {gender: "male", name: "Rafael"},
  {gender: "male", name: "Ramiro"},
  {gender: "male", name: "Ramón"},
  {gender: "male", name: "Raúl"},
  {gender: "male", name: "Ricardo"},
  {gender: "male", name: "Roberto"},
  {gender: "male", name: "Rodrigo"},
  {gender: "male", name: "Rubén"},
  {gender: "male", name: "Salvador"},
  {gender: "male", name: "Samuel"},
  {gender: "male", name: "Sancho"},
  {gender: "male", name: "Santiago"},
  {gender: "male", name: "Sergio"},
  {gender: "male", name: "Teodoro"},
  {gender: "male", name: "Timoteo"},
  {gender: "male", name: "Tomás"},
  {gender: "male", name: "Vicente"},
  {gender: "male", name: "Víctor"},
  {gender: "female", name: "Adela"},
  {gender: "female", name: "Adriana"},
  {gender: "female", name: "Alejandra"},
  {gender: "female", name: "Alicia"},
  {gender: "female", name: "Amalia"},
  {gender: "female", name: "Ana"},
  {gender: "female", name: "Ana Luisa"},
  {gender: "female", name: "Ana María"},
  {gender: "female", name: "Andrea"},
  {gender: "female", name: "Anita"},
  {gender: "female", name: "Ángela"},
  {gender: "female", name: "Antonia"},
  {gender: "female", name: "Ariadna"},
  {gender: "female", name: "Barbara"},
  {gender: "female", name: "Beatriz"},
  {gender: "female", name: "Berta"},
  {gender: "female", name: "Blanca"},
  {gender: "female", name: "Caridad"},
  {gender: "female", name: "Carla"},
  {gender: "female", name: "Carlota"},
  {gender: "female", name: "Carmen"},
  {gender: "female", name: "Carolina"},
  {gender: "female", name: "Catalina"},
  {gender: "female", name: "Cecilia"},
  {gender: "female", name: "Clara"},
  {gender: "female", name: "Claudia"},
  {gender: "female", name: "Concepción"},
  {gender: "female", name: "Conchita"},
  {gender: "female", name: "Cristina"},
  {gender: "female", name: "Daniela"},
  {gender: "female", name: "Débora"},
  {gender: "female", name: "Diana"},
  {gender: "female", name: "Dolores"},
  {gender: "female", name: "Lola"},
  {gender: "female", name: "Dorotea"},
  {gender: "female", name: "Elena"},
  {gender: "female", name: "Elisa"},
  {gender: "female", name: "Eloisa"},
  {gender: "female", name: "Elsa"},
  {gender: "female", name: "Elvira"},
  {gender: "female", name: "Emilia"},
  {gender: "female", name: "Esperanza"},
  {gender: "female", name: "Estela"},
  {gender: "female", name: "Ester"},
  {gender: "female", name: "Eva"},
  {gender: "female", name: "Florencia"},
  {gender: "female", name: "Francisca"},
  {gender: "female", name: "Gabriela"},
  {gender: "female", name: "Gloria"},
  {gender: "female", name: "Graciela"},
  {gender: "female", name: "Guadalupe"},
  {gender: "female", name: "Guillermina"},
  {gender: "female", name: "Inés"},
  {gender: "female", name: "Irene"},
  {gender: "female", name: "Isabel"},
  {gender: "female", name: "Isabela"},
  {gender: "female", name: "Josefina"},
  {gender: "female", name: "Juana"},
  {gender: "female", name: "Julia"},
  {gender: "female", name: "Laura"},
  {gender: "female", name: "Leonor"},
  {gender: "female", name: "Leticia"},
  {gender: "female", name: "Lilia"},
  {gender: "female", name: "Lorena"},
  {gender: "female", name: "Lourdes"},
  {gender: "female", name: "Lucia"},
  {gender: "female", name: "Luisa"},
  {gender: "female", name: "Luz"},
  {gender: "female", name: "Magdalena"},
  {gender: "female", name: "Manuela"},
  {gender: "female", name: "Marcela"},
  {gender: "female", name: "Margarita"},
  {gender: "female", name: "María"},
  {gender: "female", name: "María del Carmen"},
  {gender: "female", name: "María Cristina"},
  {gender: "female", name: "María Elena"},
  {gender: "female", name: "María Eugenia"},
  {gender: "female", name: "María José"},
  {gender: "female", name: "María Luisa"},
  {gender: "female", name: "María Soledad"},
  {gender: "female", name: "María Teresa"},
  {gender: "female", name: "Mariana"},
  {gender: "female", name: "Maricarmen"},
  {gender: "female", name: "Marilu"},
  {gender: "female", name: "Marisol"},
  {gender: "female", name: "Marta"},
  {gender: "female", name: "Mayte"},
  {gender: "female", name: "Mercedes"},
  {gender: "female", name: "Micaela"},
  {gender: "female", name: "Mónica"},
  {gender: "female", name: "Natalia"},
  {gender: "female", name: "Norma"},
  {gender: "female", name: "Olivia"},
  {gender: "female", name: "Patricia"},
  {gender: "female", name: "Pilar"},
  {gender: "female", name: "Ramona"},
  {gender: "female", name: "Raquel"},
  {gender: "female", name: "Rebeca"},
  {gender: "female", name: "Reina"},
  {gender: "female", name: "Rocio"},
  {gender: "female", name: "Rosa"},
  {gender: "female", name: "Rosalia"},
  {gender: "female", name: "Rosario"},
  {gender: "female", name: "Sara"},
  {gender: "female", name: "Silvia"},
  {gender: "female", name: "Sofia"},
  {gender: "female", name: "Soledad"},
  {gender: "female", name: "Sonia"},
  {gender: "female", name: "Susana"},
  {gender: "female", name: "Teresa"},
  {gender: "female", name: "Verónica"},
  {gender: "female", name: "Victoria"},
  {gender: "female", name: "Virginia"},
  {gender: "female", name: "Yolanda"}
  ]
